# -*- coding: utf-8 -*-
"""4 March Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U1DfKPTVoGu9VGJF62-Pf60SBNg5WTu5
"""

#Que1
import seaborn as sns
titanic=sns.load_dataset('titanic')

titanic

import plotly.graph_objects as go

import plotly.graph_objects as go

fig=go.Figure()
fig.add_trace(go.Scatter(x=titanic['age'],y=titanic['fare'],mode='markers'))

#Que2
tips_data=sns.load_dataset('tips')

tips_data

tips_data = sns.load_dataset("tips")

box_trace = go.Box(x=tips_data["day"], y=tips_data["total_bill"])
fig = go.Figure(box_trace)

fig

#Que3
tips_data = sns.load_dataset("tips")

tips_data

import plotly.express as px

hist_fig = px.histogram(tips_data, x="sex", y="total_bill", color="day", pattern_shape="smoker")
hist_fig.show()

#Que4
iris=sns.load_dataset('iris')

iris

scatter_matrix_fig = px.scatter_matrix(data_frame=iris, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], color="species")
scatter_matrix_fig.show()

#Que5
'''Distplot is a function from the seaborn library used to plot a univariate distribution of observations. It combines a histogram with a kernel density estimate to provide a smoothed curve showing the shape of the distribution.

To plot a distplot using Plotly express, we can use the px.histogram() function with the marginal parameter set to "rug". This will add a rug plot to the x-axis, showing the individual observations in addition to the histogram and density curve.'''

import plotly.express as px

tips_data = sns.load_dataset("tips")

tips_data = sns.load_dataset("tips")

tips_data

fig = px.histogram(tips_data, x="total_bill", color="sex", nbins=20, opacity=0.7, barmode="relative")
fig.show()

